services:
  hanami:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanami
    ports:
      - "8080:8080"
    container_name: hanami-container
    depends_on:
      hanami-db:
          condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://hanami-db:3306/${MYSQL_DATABASE:-hanami_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-hanami_user}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-hanami_password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  hanami-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-hanami_db}
      - MYSQL_USER=${MYSQL_USER:-hanami_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-hanami_password}
    ports:
      - "3306:3306"
    container_name: hanami-db-container
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: