services:
  hanami:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanami
    ports:
      - "8080:8080"
    container_name: hanami-container
  hanami-db:
    image: mysql:8.0
    environment:
      - MYSQL_USER=hanami_user
      - MYSQL_PASSWORD=hanami_password
      - MYSQL_DB=hanami_db
    ports:
      - "3306:3306"
    container_name: hanami-db-container
